[package]
name = "actix-client-timeout"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.4"
actix-web = "0.7.8"
futures = "0.1"
env_logger = "*"