[package]
name = "actix06-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]

[dependencies]
mdo = "0.3"
mdo-future = "0.2"
futures = "0.1"
actix = "0.6"
tokio = "0.1"
tokio-timer = "0.2"