[package]
name = "hello_world"
version = "0.0.1"
authors = [ "legokichi <legokichi@gmail.com>" ]

[dependencies]
serde = " 1 "
serde_json = " 1 "
serde_derive = " 1 "


[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = { git = "https://github.com/gifnksm/emscripten-sys.git" }
stdweb = { git = "https://github.com/koute/stdweb.git" }
