[package]
name = "timer-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]

[dependencies]
mdo = "0.3"
mdo-future = "0.2"
actix = "0.5"
tokio-core = "0.1"
futures = "0.1"
tokio = { git = "https://github.com/tokio-rs/tokio.git", commit = "24d99c029eff5d5b82aff567f1ad5ede8a8c2576" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio.git", commit = "24d99c029eff5d5b82aff567f1ad5ede8a8c2576" }
