[package]
name = "timer-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]


[workspace]
members = [
    "./",
    "actix05-example",
    "actix06-example",
    "tokio-core-example",
    "tokio-runtime-example",
]


[dependencies]
mdo = "0.3"
mdo-future = "0.2"
actix = "0.5"
tokio-core = "0.1"
futures = "0.1"
tokio = "0.1.7"
tokio-timer = "0.2.4"
