[package]
name = "rumqtt-alpn-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqtt = { git = "https://github.com/Idein/rumqtt", branch = "alpn-support" }
dotenv = "0.14"
env_logger = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
log-derive = "0.3"
runtime = { version = "0.3.0-alpha.5", default-features = true }
runtime-tokio = "0.3.0-alpha.5"
futures-preview = { version = "=0.3.0-alpha.16", features = ["async-await", "nightly"] }
tokio-timer = "0.2"
tokio-fs = "0.1"
envy = "0.4"
failure = "0.1"

[dev-dependencies]

