[package]
name = "tokio-runtime-example"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]

[dependencies]
mdo = "0.3"
mdo-future = "0.2"
futures = "0.1"
tokio = "0.1.7"
tokio-timer = "0.2.4"
