[package]
name = "foo-derive"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15.17", features = ["visit", "extra-traits", "full"] }
quote = "0.6"
