comment_width = 1000
normalize_comments = true
reorder_imports = false
reorder_modules = false
reorder_impl_items = false
report_todo = "Always"
report_fixme = "Always"
use_field_init_shorthand = true
ignore = [
    "src/build.rs",
]
