[package]
name = "actix_web_err"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]

[dependencies]
futures = "0.1"
actix-web  = "0.7"
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"