[package]
name = "rl"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
libmath = "0.2"
rayon = "1.0"
ndarray = { version = "0.12" }
statrs = "0.10"
serde = { version ="1.0",  features = ["derive"] }
serde_json = "1.0"