[package]
name = "tw-fav"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.13"
egg-mode = { git = "https://github.com/QuietMisdreavus/twitter-rs" }
env_logger = "0.6"
envy = "0.3"
futures = "0.1"
hyper = "0.12"
hyper-tls = { version = "0.3", optional = true }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
