[package]
name = "tw-fav"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.15"
egg-mode = { git = "https://github.com/QuietMisdreavus/twitter-rs", branch = "master" }
env_logger = "0.7"
envy = "0.4"
err-derive = "0.2"
futures = { version = "0.3", features = [] }
log = "0.4"
reqwest = "0.10"
rustyline = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { git = "https://github.com/clap-rs/clap", branch = "master" }
tokio = { version = "0.2", features = ["fs", "time"] }

