[package]
name = "tw-fav"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.14"
egg-mode = { git = "https://github.com/QuietMisdreavus/twitter-rs", branch = "master" }
env_logger = "0.7"
envy = "0.4"
err-derive = "0.1"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
futures-util-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
log = "0.4"
reqwest = "0.9"
runtime = { version = "0.3.0-alpha.7", default-features = true }
runtime-tokio = "0.3.0-alpha.6"
rustyline = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { git = "https://github.com/TeXitoi/structopt", branch = "master" }
tokio = "0.1"
tokio-fs = "0.1"
tokio-timer = "0.2"
