[package]
name = "lapin-stream"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]

[dependencies]
futures = "0.1"
lapin-futures = "0.13"
tokio = "0.1"
tokio-io = "0.1"
tokio-dns-unofficial = "0.3"
log = "0.4"
env_logger = "0.5"
mdo = "0.3"
mdo-future = "0.2"
failure = "0.1"
tokio-timer = "0.2"
uuid = { features = ["v4"], version = "0.6" }

