[package]
name = "nostd"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wee_alloc = "0.4"
# console_error_panic_hook = "0.1"
heapless = "0.5"

[profile.release]
lto = true
