[package]
name = "actix-web-longpoll"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]


[dependencies]
actix-web = { path = "../../actix-web"}
futures = "0.1"
env_logger = "0.5"
log = "0.4.1"
tokio-timer = "0.2"
failure = "0.1"