[package]
name = "iso-rust2"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.js-sys]
path = "../wasm-bindgen/crates/js-sys/"

[dependencies.web-sys]
path = "../wasm-bindgen/crates/web-sys/"
features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
]