[package]
name = "proptest-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
envy = "0.3"
dotenv = "0.13"
env_logger = "0.6"
proptest   = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
failure = "0.1"