[package]
name = "proptest-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
base64-serde = "0.3"
chrono = { features = ["serde"], version = "0.4" }
dotenv = "0.13"
env_logger = "0.6"
envy = "0.3"
failure = "0.1"
log = "0.4"
proptest = "0.9"
proptest-derive = "0.1"
regex = "1.0"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_regex = "0.3"
url = "1.7"
url_serde = "0.2"
uuid = { features = ["serde", "v4"], version = "0.6" }
