[workspace]
members = ["model-a", "model-b"]


[package]
name = "frunk-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

[dependencies]
model-a = {path="./model-a"}
model-b = {path="./model-b"}
frunk = { version = "0.3", features = ["serde"] }
frunk_core = { version = "0.3", features = ["serde"] }
derive_more = "0.99"
frunk-enum-core = "0.2"
frunk-enum-derive = "0.2"
